backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: "src/images/uploads"
public_folder: "images/uploads"

search: false

collections:
  - name: "pos"
    label: "Pos"
    folder: "src/pos"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}