backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

search: false

collections:
  - label: "Pos"
    name: "pos"
    folder: "src/pos"
    create: true
    preview_path: "pos/{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Time", name: "date", widget: "datetime", date_format: "DD/MM/YYY", time_format: "HH:mm"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "code", "link", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]}
      - {label: "Tags", name: "tags", widget: "hidden", default: "pos"}
  - label: "Settings"
    name: "settings"
    files:
      - label: "General"
        name: "general"
        file: "src/_data/settings.json"
        fields:
          - {label: "Site name", name: "sitename", widget: "string"}
          - {label: "Site description", name: "description", widget: "string"}
          - {label: "Banner", name: "banner", widget: "image", "allow_multiple": false}
