backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: "src/images/uploads"
public_folder: "images/uploads"

search: false

collections:
  - name: "pos"
    label: "Pos"
    folder: "src/pos"
    create: true
    preview_path: "blog/{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "select", options: ["lorem", "ipsum"], multiple: true, min: 1}